const { graphqlHTTP } = require('express-graphql')
const gql = require('graphql-tag')
const { buildASTSchema } = require('graphql')
const  { ingData } = require('./ingData.json')
const expressPlayground = require('graphql-playground-middleware-express')